# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
version: "3.3"

# Servidor nginx
services:
  web:
    # versión
    image: nginx:latest
    # Puerto 8080 
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  # Configuración de php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html