CREATE TABLE EQUIP
(
  ID NUMBER NOT NULL,
  NOM VARCHAR2(20),
  CONSTRAINT EQUIP_PK PRIMARY KEY (ID) ENABLE
);

CREATE SEQUENCE EQUIP_SEQ;

CREATE TRIGGER EQUIP_TRG
BEFORE INSERT ON EQUIP
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EQUIP_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
